### ISSUE TITLE
Error in config

### ISSUE THREAD

**Issue by ewal** [DylanLukes/bootstrap-sass-webpack#2]
I've specified a custom configuration inside the entry in my webpack.config, but I get this error. (I've also tried without the custom config with no luck).

ERROR in ./~/bootstrap-sass-webpack/~/css-loader!./~/sass-loader!./~/bootstrap-sass-webpack/bootstrap-sass-styles.loader.js!./bootstrap-sass.config.js
Module build failed:
  scripts: {
^
      Error reading values after @icon-font-path
in /[path to project]/bootstrap-sass.config.js (line 2, column 1)
 @ ./~/bootstrap-sass-webpack/~/style-loader!./~/bootstrap-sass-webpack/~/css-loader!./~/sass-loader!./~/bootstrap-sass-webpack/bootstrap-sass-styles.loader.js!./bootstrap-sass.config.js 4:2-402

Any ideas?

**Comment by shark0der** [comment]
Same weird error here, did you manage to solve it?

**Comment by johanforssell** [comment]
I have the exact same result, even though I've not created any custom configuration
:+1:

**Comment by datapimp** [comment]
This error still happens with the latest NPM release in a pretty much vanilla webpack configuration, if you follow the readme.

Not able to solve it yet.

**Comment by b-d-m-p** [comment]
Same here. 

Just to clarify, we should be copying these config files and putting them somewhere in our project outside of the npm package and pointing to that in case we have to update it, right?

**Comment by bes** [comment]
I got this issue as well

**Comment by keown** [comment]
+1

**Comment by sja** [comment]
@datapimp You mean, that switching to an older version of npm can solve that?

**Comment by e11it** [comment]
+1

**Comment by rankers** [comment]
+1

**Comment by mathiasbronner** [comment]
+1

**Comment by asharma93** [comment]
+1

**Comment by lisannefoget** [comment]
+1

**Comment by jessemezini** [comment]
+1

**Comment by DylanLukes** [comment]
I am not able to actively maintain this :(. 

I just made this as a one-off for one of my own projects. Anyone willing to fork it? Or can these changes go upstream?
